name: Deploy to ConoHa VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Pack project
        run: dotnet pack --configuration Release --no-build --output ./nupkg

      - name: Create .ssh directory and add known hosts
        env:
          HOST: ${{ secrets.HOST }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 $HOST >> ~/.ssh/known_hosts

      - name: Create deployment directory
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh $USERNAME@$HOST -i private_key -p 22 "mkdir -p pokenaeNugetPackage"

      - name: Deploy to ConoHa VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          rsync -avz -e "ssh -i private_key -p 22" ./nupkg/*.nupkg $USERNAME@$HOST:pokenaeNugetPackage