name: Publish NuGet Package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Increment version
      id: increment_version
      run: |
        VERSION_FILE="Directory.Build.props"
        VERSION_PREFIX=$(grep -oP '(?<=<VersionPrefix>)[^<]+' $VERSION_FILE)
        VERSION_SUFFIX=$(grep -oP '(?<=<VersionSuffix>)[^<]+' $VERSION_FILE)
        NEW_VERSION_SUFFIX=$((VERSION_SUFFIX + 1))
        sed -i "s/<VersionSuffix>$VERSION_SUFFIX<\/VersionSuffix>/<VersionSuffix>$NEW_VERSION_SUFFIX<\/VersionSuffix>/" $VERSION_FILE
        echo "New version: $VERSION_PREFIX.$NEW_VERSION_SUFFIX"
        echo "new_version=$VERSION_PREFIX.$NEW_VERSION_SUFFIX" >> $GITHUB_ENV

    - name: Build project
      run: dotnet build --configuration Release

    - name: Pack project
      run: dotnet pack --configuration Release --output ./nupkg

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

    - name: Commit version increment
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add Directory.Build.props
        git commit -m "Increment version to ${{ env.new_version }}"
        git push